### ISSUE TITLE
Problems with map UID [TMF]

### ISSUE THREAD

**Issue by 3zet** [EvoEsports/minicontrol#23]
Tried to run it on a fresh server. Both minicontrol and server are running natively. Clean, untouched tmf server files. OS is a freshly installed Debian 12.

```
$ drizzle-kit generate:sqlite --config=drizzle.config.ts && bun --smol core/minicontrol.ts
drizzle-kit: v0.20.14
drizzle-orm: v0.30.6

Reading config file '/minicontrol-0.3.7/drizzle.config.ts'
4 tables
map 8 columns 2 indexes 0 fks
maplikes 6 columns 0 indexes 2 fks
player 6 columns 1 indexes 0 fks
records 8 columns 2 indexes 2 fks

No schema changes, nothing to migrate 😴Starting MiniControl...
Connecting to Trackmania Dedicated server at localhost:5000
Connected to Trackmania Dedicated server.
71 |             }
72 | 
73 |             let res = await tmc.server.multicall(out) || [];
74 | 
75 |             for (const map of res) {
76 |                 this.maps[map.UId] = map;
                               ^
TypeError: undefined is not an object (evaluating 'map.UId')
      at /minicontrol-0.3.7/core/mapmanager.ts:76:27

Bun v1.1.13 (Linux x64)
error: script "start" exited with code 1
```

To be honest, I wrote some extra code which instead of killing minicontrol it shows undefined map message and throws database error but its most likely due to lack of map ID. 

Error is the same when running both minicontrol and a server in containers. Tried also that example container with both game and minicontrol.

**Comment by reaby** [comment]
This is now fixed at dev branch now.
I was working tm2020 so forgot to double check tmnf support.
