### ISSUE TITLE
"Command /maps not found." [TMF]

### ISSUE THREAD

**Issue by 3zet** [EvoEsports/minicontrol#26]
I don't know if it is a planned feature or is just not working, I'm posting it here just in case. 
![maps_not_found](https://github.com/EvoEsports/minicontrol/assets/69508064/3428c999-126b-44e2-b0f3-6f22debd5731)

**Comment by reaby** [comment]
already fixed at dev branch, as well the colors not working with tmnf

**Comment by reaby** [comment]
feel free to join evo discord, there's dedicated minicontrol channel for discussions.
