### ISSUE TITLE
see if its possible to start app with windows version of nodejs.

### ISSUE THREAD

**Issue by reaby** [EvoEsports/minicontrol#32]
While the linux version works nicely without issues, the windows version has currently these issues:

- [ ] core is not package, aka there's issue of ESM class loader with custom path-to-class resolver
- [ ] paths are not working since:  --> d: is not file:// protocol
- [ ] all plugin names are null when trying to load at startup

**Comment by Chris92de** [comment]
Fixed with [ae42c076ae86fa12972438c4c4f1a34689a3172f](https://github.com/EvoEsports/minicontrol/commit/ae42c076ae86fa12972438c4c4f1a34689a3172f)
