### ISSUE TITLE
TMX plugin needs to check for Unlimiter map requirement in TMNF/TMUF

### ISSUE THREAD

**Issue by Chris92de** [EvoEsports/minicontrol#43]
- [ ]  Block adding Unlimiter maps to server by default
- [ ]  Add config option to allow adding Unlimiter maps

**Comment by reaby** [comment]
This is going forward. I'm waiting pull request and update to gbx-ts to be processed and the library to update.
ref: https://github.com/thaumictom/gbx-ts/pull/7
