### ISSUE TITLE
Implementing an automatic notification message whenever a dedi is set.

### ISSUE THREAD

**Issue by VZCE** [EvoEsports/minicontrol#52]
It feels odd to see local record messages but no dedi notifications at all. Everyone enjoys seeing dedis and reacting to the times achieved in real time.

**Comment by Chris92de** [comment]
We can probably add this to `core/plugins/announces`, shouldn't be hard to implement.
Thanks for suggestion.

**Comment by reaby** [comment]
done with 0.6.1
